# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019
  demands:
  - msbuild
  - visualstudio

steps:
# ...
# Use NuGet 5.0
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.0'
  inputs:
    versionSpec: 5.0.x
# ...
# Restore NuGet packages.
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    feedsToUse: config
# ...
# Build Solution
- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    platform: 'any cpu'
  condition: succeededOrFailed()